CinemaApp/Controllers/MoviesController.cs
using CinemaApp.Data;
using CinemaApp.Models.Domain;
using CinemaApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CinemaApp.Controllers
{
    public class MoviesController : Controller
    {
        private readonly MVCCinemaDBContext mvc;

        private List<Theater> theaters;

        public MoviesController(MVCCinemaDBContext mvc)
        {
            this.mvc = mvc;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var movies = await mvc.Movies
              .Join(
                mvc.Theaters, // Join with Theaters table
                movie => movie.TheaterID, // Join on Movie's TheaterID
                theater => theater.Id,     // Join on Theater's Id
                (movie, theater) => new IndexMovieViewModel
                {
                    Id = movie.Id,
                    Name = movie.Name,
                    PremiereDate = movie.PremiereDate,
                    FinalDate = movie.FinalDate,
                    TheaterID = movie.TheaterID, // Retrieve theater ID
                    TheaterName = theater.Name   // Retrieve theater name
                }
              ).ToListAsync();

            return View(movies);
        }

        [HttpGet]
        public async Task<IActionResult> Add()
        {
            theaters = await mvc.Theaters.ToListAsync();
            ViewBag.Theaters = new SelectList(theaters, "Id", "Name");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddMovieViewModel model)
        {
            var movie = new Movie()
            {
                Id = Guid.NewGuid(),
                Name = model.Name,
                TheaterID = model.TheaterID,
                PremiereDate = model.PremiereDate,    
                FinalDate = model.FinalDate,
            };

            await mvc.Movies.AddAsync(movie);
            await mvc.SaveChangesAsync();
            return RedirectToAction("Add");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid ID)
        {
            theaters = await mvc.Theaters.ToListAsync();
            ViewBag.Theaters = new SelectList(theaters, "Id", "Name");

            var movie = await mvc.Movies.FirstOrDefaultAsync(x => x.Id == ID);

            if (movie != null)
            {
                var model = await mvc.Movies
                    .Where(movie => movie.Id == ID)
                  .Join(
                    mvc.Theaters, // Join with Theaters table
                    movie => movie.TheaterID, // Join on Movie's TheaterID
                    theater => theater.Id,     // Join on Theater's Id
                    (movie, theater) => new UpdateMovieViewModel
                    {
                        Id = movie.Id,
                        Name = movie.Name,
                        PremiereDate = movie.PremiereDate,
                        FinalDate = movie.FinalDate,
                        TheaterID = movie.TheaterID, // Retrieve theater ID
                        TheaterName = theater.Name   // Retrieve theater name
                    }
                  ).FirstOrDefaultAsync();

                return await Task.Run(() => View("Edit", model));
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Edit(UpdateMovieViewModel model)
        {
            var rec = await mvc.Movies.FindAsync(model.Id);

            if (rec != null)
            {
                rec.Id = model.Id;
                rec.Name = model.Name;
                rec.TheaterID = model.TheaterID;
                rec.PremiereDate = model.PremiereDate;
                rec.FinalDate = model.FinalDate;

                await mvc.SaveChangesAsync();
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> View(Guid ID)
        {

            var movie = await mvc.Movies.FirstOrDefaultAsync(x => x.Id == ID);

            if (movie != null)
            {
                var viewModel = await mvc.Movies
                    .Where(movie => movie.Id == ID)
                  .Join(
                    mvc.Theaters, // Join with Theaters table
                    movie => movie.TheaterID, // Join on Movie's TheaterID
                    theater => theater.Id,     // Join on Theater's Id
                    (movie, theater) => new IndexMovieViewModel
                    {
                        Id = movie.Id,
                        Name = movie.Name,
                        PremiereDate = movie.PremiereDate,
                        FinalDate = movie.FinalDate,
                        TheaterID = movie.TheaterID, // Retrieve theater ID
                        TheaterName = theater.Name   // Retrieve theater name
                    }
                  ).FirstOrDefaultAsync();

                return await Task.Run(() => View("View", viewModel));
            }
            return RedirectToAction("Index");

        }

        [HttpPost]
        public async Task<IActionResult> Delete(UpdateTheaterViewModel model)
        {
            var rec = await mvc.Movies.FindAsync(model.Id);

            if (rec != null)
            {
                mvc.Movies.Remove(rec);
                await mvc.SaveChangesAsync();
            }
            return RedirectToAction("Index");

        }

    }
}

CinemaApp/Controllers/TheatersController.cs
using CinemaApp.Data;
using CinemaApp.Models;
using CinemaApp.Models.Domain;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Reflection.Metadata.Ecma335;

namespace CinemaApp.Controllers
{
    public class TheatersController : Controller
    {
        private readonly MVCCinemaDBContext mvc;

        public TheatersController(MVCCinemaDBContext mvc)
        {
            this.mvc = mvc;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var theaters = await mvc.Theaters.ToListAsync();
            return View(theaters);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddTheaterViewModel addTheaterRequest)
        {
            var theater = new Theater()
            {
                Id = Guid.NewGuid(),
                Name = addTheaterRequest.Name,
                City = addTheaterRequest.City,
                TicketPrice = addTheaterRequest.TicketPrice,
                OpenHoursFrom = addTheaterRequest.OpenHoursFrom,
                OpenHoursTo = addTheaterRequest.OpenHoursTo
            };
            //return View(theater);
            await mvc.Theaters.AddAsync(theater);
            await mvc.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid ID)
        {
            var theater = await mvc.Theaters.FirstOrDefaultAsync(x => x.Id == ID);

            if (theater != null)
            {
                var viewModel = new UpdateTheaterViewModel()
                {
                    Id = theater.Id,
                    Name = theater.Name,
                    City = theater.City,
                    TicketPrice = theater.TicketPrice,
                    OpenHoursFrom = theater.OpenHoursFrom,
                    OpenHoursTo = theater.OpenHoursTo
                };
                return await Task.Run(() => View("Edit",viewModel));
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Edit(UpdateTheaterViewModel model)
        {
            var rec = await mvc.Theaters.FindAsync(model.Id);

            if (rec != null)
            {
                rec.Id = model.Id;
                rec.Name = model.Name;
                rec.City = model.City;
                rec.TicketPrice = model.TicketPrice;
                rec.OpenHoursFrom = model.OpenHoursFrom;
                rec.OpenHoursTo = model.OpenHoursTo;

                await mvc.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> View(Guid ID)
        {
            var theater = await mvc.Theaters.FirstOrDefaultAsync(x => x.Id == ID);

            if (theater != null)
            {
                var viewModel = new UpdateTheaterViewModel()
                {
                    Id = theater.Id,
                    Name = theater.Name,
                    City = theater.City,
                    TicketPrice = theater.TicketPrice,
                    OpenHoursFrom = theater.OpenHoursFrom,
                    OpenHoursTo = theater.OpenHoursTo
                };
                return await Task.Run(() => View("View", viewModel));
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(UpdateTheaterViewModel model)
        {
            var rec = await mvc.Theaters.FindAsync(model.Id);

            if (rec != null)
            {
                mvc.Theaters.Remove(rec);
                await mvc.SaveChangesAsync();
            }
            return RedirectToAction("Index");

        }

    }
}

CinemaApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CinemaApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CinemaApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CinemaApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Theaters" asp-action="Index">List Theaters</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Theaters" asp-action="Add">Add Theater</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movies" asp-action="Index">List Movies</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movies" asp-action="Add">Add Movie</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - CinemaApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>